/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rvs.h"
#include <stdio.h>

CLIENT *rpc_setup(char *host);
int add_voter_rpc(CLIENT *clnt, int voter_id);



int
main (int argc, char *argv[])
{   CLIENT *clnt;
    char *host;
    int voter_id;
    if (argc < 3) {
        printf ("usage: %s server_ip_address voter_id\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    
    if((voter_id=atoi(argv[2]))==0&&*argv[2]!='0'){
        fprintf(stderr,"invalidvalue:%s\n",argv[2]);
        exit(1);
    }
    if((clnt=rpc_setup(host))==0) exit(1);
    add_voter_rpc(clnt,voter_id);
    clnt_destroy(clnt);
    exit (0);
}

CLIENT *
rpc_setup(char *host){
    CLIENT *clnt = clnt_create (host, VS_PROG, VS_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        return 0;
    }
    return clnt;
    
}

int add_voter_rpc(CLIENT *clnt, int voter_id){
    int  *result_2;
    int  addvoter_1_arg;
    
    addvoter_1_arg = voter_id;
//    printf("addvoter_1_arg: %d\n",addvoter_1_arg);
    result_2 = addvoter_1(&addvoter_1_arg, clnt);
    if (result_2 == (int *) NULL) {
        clnt_perror (clnt, "call failed");
    }
    
    
    else if(*result_2 == 1){
        printf("Added one voter!\n");
    }
    else if(*result_2==0){
        printf("This voter already exists\n");
    }
    else if(*result_2==-1){
        printf("Add one voter failed\n");
    }
    
}

