/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RVS_H_RPCGEN
#define _RVS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TRUE 1
#define FALSE 0
#define OK 1
#define EXISTS 0
#define ERROR -1
#define NEW 1
#define NOTAVOTER -1
#define ALREADYVOTED -2
#define MAX_C 5
#define MAX_V 100

struct vote {
	char can_name[40];
	int voter_id;
};
typedef struct vote vote;

#define VS_PROG 0x30090949
#define VS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define zeroize 1
extern  int * zeroize_1(void *, CLIENT *);
extern  int * zeroize_1_svc(void *, struct svc_req *);
#define addvoter 2
extern  int * addvoter_1(int *, CLIENT *);
extern  int * addvoter_1_svc(int *, struct svc_req *);
#define votefor 3
extern  int * votefor_1(vote *, CLIENT *);
extern  int * votefor_1_svc(vote *, struct svc_req *);
#define listcandidates 4
extern  char ** listcandidates_1(void *, CLIENT *);
extern  char ** listcandidates_1_svc(void *, struct svc_req *);
#define votecount 5
extern  int * votecount_1(char **, CLIENT *);
extern  int * votecount_1_svc(char **, struct svc_req *);
extern int vs_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define zeroize 1
extern  int * zeroize_1();
extern  int * zeroize_1_svc();
#define addvoter 2
extern  int * addvoter_1();
extern  int * addvoter_1_svc();
#define votefor 3
extern  int * votefor_1();
extern  int * votefor_1_svc();
#define listcandidates 4
extern  char ** listcandidates_1();
extern  char ** listcandidates_1_svc();
#define votecount 5
extern  int * votecount_1();
extern  int * votecount_1_svc();
extern int vs_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vote (XDR *, vote*);

#else /* K&R C */
extern bool_t xdr_vote ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RVS_H_RPCGEN */
