/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rvs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define TRUE 1
#define FALSE 0

#define OK 1
#define EXISTS 0
#define ERROR -1


//#define EXISTS 0
#define NEW 1
#define NOTAVOTER -1
#define ALREADYVOTED -2


struct Voter{
    int id;
    /*
     0 : FALSE
     1, or anything other than 0 : TRUE*/
    int has_voted;
    
};

struct Candidate{
    char *name;
    int votes;
};

typedef struct Voter voter;
typedef struct Candidate candidate;

#define MAX_C 5
#define MAX_V 100
#define MAX_NAME 30
#define MAX_BUFF 2048
#define MAX_LINE 50



candidate candidate_list[MAX_C];
voter voter_list[MAX_V];








int *
zeroize_1_svc(void *argp, struct svc_req *rqstp)
{
    static int  result;
    int i;
    int j;
    for ( i = 0; i<MAX_V; i++) {
        //id is -1 means no voer
        voter_list[i].id = -1;
        voter_list[i].has_voted = 0;
        
    }
    for ( j =0; j<MAX_C; j++) {
        candidate_list[j].votes = 0;
        candidate_list[j].name = NULL;
    }
    if(i==MAX_V&&j==MAX_C){
        printf("true\n");
        result =  TRUE;
        return &result;
    }
    else {
        printf("false\n");
        result =  FALSE;
        return &result;
    }
    
    
    return &result;
}

int *
addvoter_1_svc(int *argp, struct svc_req *rqstp)
{
    
    static int  result;
    
    int voterid = *argp;
    //voterid can be out of 0-29
    int i;
    for (i = 0; i<MAX_V; i++) {
        if(voter_list[i].id ==-1){
            voter_list[i].id = voterid;
//            printf("input_id: %d",voterid);
//            printf("i: %d ", i);
//            printf("id: %d\n ",voter_list[i].id);
            printf("ok\n");
            result = OK;
            return &result;
            
            
        }
        if(voter_list[i].id==voterid){
//            printf("i: %d", i);
//            printf("id: %d\n ",voter_list[i].id);
//            printf("exists\n");
            result =  EXISTS;
            return &result;
            
        }
        
    }
    result =  ERROR;
    
    
    return &result;
}

int *
votefor_1_svc(vote *argp, struct svc_req *rqstp)
{
    static int  result;
    
    int voterid = argp->voter_id;
    char name[MAX_NAME];
//    printf("argp->can_name: %s\n", argp->can_name);
    strcpy(name, argp->can_name);
//    printf("name:%s\n", name);
    
    int j;
    for(j = 0;j<MAX_V;j++){
        if(voter_list[j].id==voterid){
            if(voter_list[j].has_voted==0) {//has not voted yet, so set to 1
                voter_list[j].has_voted =1;
                break;
            }
            else {
                printf("alreadyvoted\n");
                result = ALREADYVOTED;
                return &result;
            }
        }
    }
    
    if(j==MAX_V) {
        printf("notavoter\n");
        result = NOTAVOTER;
        return &result;
    }
    
    int i;
    for (i =0; i<MAX_C; i++) {
        
        if(candidate_list[i].name==NULL) {
            candidate_list[i].name = (char*)malloc(sizeof(strlen(name)));
            if (candidate_list[i].name==NULL) {
                printf("error\n");
                result = ERROR;
                return &result;
                
            }
            strcpy(candidate_list[i].name, name);
            candidate_list[i].votes =1;
//            printf("candidate[i]:%s\n",candidate_list[i]);
            printf("new\n");
            fflush(stdout);
            result = NEW;
            return &result;
            
        }
        
        if (strcmp(candidate_list[i].name,name)==0) {
            candidate_list[i].votes++;
            printf("exists\n");
            result = EXISTS;
            return &result;
            
        }
        
    }
    
    result = ERROR;
    
    
    return &result;
}

char **
listcandidates_1_svc(void *argp, struct svc_req *rqstp)
{
    static char *result;
    char line[MAX_LINE];
    char buf[MAX_BUFF];
    int idx = 0;
    while (candidate_list[idx].name!=NULL) {
//        printf("candidate_list[idx].name: %s\n", candidate_list[idx].name);
        sprintf(line, "%s  : %d\n", candidate_list[idx].name,candidate_list[idx].votes);
        strcat(buf, line);
//        printf("idx:%d\n",idx);
        idx++;
    }
    
    if(idx==0) sprintf(buf, "There is no candidate yet\n");
    result = buf;
    return &result;
}

int *
votecount_1_svc(char **argp, struct svc_req *rqstp)
{
    static int  result;
    int tmp;
    char name[MAX_NAME];
//    printf("*argp:%s\n",*argp);
    strcpy(name, (*argp));
    int i;
    for (i =0; i<MAX_C; i++) {
//        printf("candidate_list[i].name: %s\n",candidate_list[i].name);
        if(candidate_list[i].name==NULL){
            break;
            
        }
        if (strcmp(candidate_list[i].name,name)==0) {
            
            tmp = candidate_list[i].votes;
            result = tmp;
            return &result;
            
        }
    }
    
    result = -1;
    
    return &result;
}
