/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rvs.h"
#include <stdio.h>


void
vs_prog_1(char *host, char *name)
{
    
    CLIENT *clnt;
    
    int  *result_5;
    char * votecount_1_arg;
    
    
#ifndef	DEBUG
    clnt = clnt_create (host, VS_PROG, VS_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif	/* DEBUG */
    strcpy(votecount_1_arg,name);
//    printf("votecount_1_arg: %s\n", votecount_1_arg);
    
    
    result_5 = votecount_1(&votecount_1_arg, clnt);
//    printf("*result_5:%d\n",(*result_5));
    if (result_5 == (int *) NULL) {
        clnt_perror (clnt, "call failed");
    }
    
    else if((*result_5) == -1){
        printf("%s is not in the system\n",name);
    }
    else if((*result_5)>-1){
        printf("There are %d votes for %s\n",(*result_5),name);
    }
    else{
        
    }
    
#ifndef	DEBUG
    clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
    char *host;
    char name[40];
    if (argc < 3) {
        printf ("usage: %s server_ip_address candidate_name\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    strcpy(name, argv[2]);
    vs_prog_1 (host, name);
    
    exit (0);
}
