/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rvs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

CLIENT *rpc_setup(char *host);
int vote_rpc(CLIENT *clnt, char* name, int voter_id);

int
main (int argc, char *argv[])
{
    CLIENT *clnt;
    char *host;
    int voter_id;
    char* name;
    if (argc < 4) {
        printf ("usage: %s server_ip_address, candidate_name, voter_id\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    strcpy(name, argv[2]);
    if((voter_id=atoi(argv[3]))==0&&*argv[3]!='0'){
        fprintf(stderr,"invalidvalue:%s\n",argv[3]);
        exit(1);
    }
    if((clnt=rpc_setup(host))==0) exit(1);
    vote_rpc(clnt,name,voter_id);
    clnt_destroy(clnt);
    exit (0);
}



CLIENT *
rpc_setup(char *host){
    CLIENT *clnt = clnt_create (host, VS_PROG, VS_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        return 0;
    }
    return clnt;
    
}


int vote_rpc(CLIENT *clnt, char* name, int voter_id){
    int  *result_3;
    vote  votefor_1_arg;
    
    votefor_1_arg.voter_id = voter_id;
    strcpy(votefor_1_arg.can_name,name);
//    printf("votefor_1_arg: %s\n", votefor_1_arg.can_name);
    result_3 = votefor_1(&votefor_1_arg, clnt);
    
    if (result_3 == (int *) NULL) {
        clnt_perror (clnt, "call failed");
    }
    
    else if(*result_3 == 1){
        printf("This candidate is new\n");
    }
    else if(*result_3==0){
        printf("This candidate already exists\n");
    }
    else if(*result_3==-1){
        printf("This voter is not authorized to vote\n");
    }
    else if(*result_3==-2){
        printf("This voter already voted\n");
    }

}
